version: '3'
services:
  client:
    build: client
    ports:
      - '8080:8080'
  server:
    build: server
    environment:
      - PORT=3000
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost:8080
      - JWT_SECRET=my_secret
      - MONGO_URI=mongodb+srv://mern-sess:DgickkNiyZoUQ2sd@mern-sess.sokjozx.mongodb.net/?retryWrites=true&w=majority&appName=mern-sess
    ports:
      - '3000:3000'
